import { useRef, useState } from 'react';
import { Image, Pressable, Text, TextInput, View } from 'react-native';
import * as Crypto from 'expo-crypto';
import { useAccount } from './AccountConnection';
import { Button, colors } from './Studio';
import type { AccountPhoto, Property } from '../lib/account-api';
type Choice={preview:string;jeton:string;key:string;selected:boolean};
export function ConnectedListingImport({ onImported, usage = 'photo' }: { onImported:(ids:string[])=>void; usage?: 'photo' | 'video' }) {
 const {api}=useAccount();const [open,setOpen]=useState(false);const [homeCreated,setHomeCreated]=useState(false);const [url,setUrl]=useState('');const [title,setTitle]=useState('');const [photos,setPhotos]=useState<Choice[]>([]);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const home=useRef('');const imported=useRef<string[]>([]);
 async function find(){if(busy)return;setBusy(true);setNotice('Recherche des photos…');try{const result=await api.json<{titre:string;photos:{preview:string;jeton:string}[];message:string}>('/annonces/photos',{method:'POST',body:JSON.stringify({url})});setTitle(result.titre);setPhotos(result.photos.map(p=>({...p,key:Crypto.randomUUID(),selected:true})));setNotice(result.message);}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 async function add(){if(busy)return;setBusy(true);try{if(!home.current){const result=await api.json<Property>('/logements',{method:'POST',body:JSON.stringify({nom:title,source_url:url})});home.current=result.id;setHomeCreated(true);}for(const photo of photos.filter(p=>p.selected)){setNotice(`Ajout des photos : ${imported.current.length} enregistrée(s)…`);const result=await api.json<AccountPhoto>('/annonces/importer',{method:'POST',body:JSON.stringify({logement_id:home.current,jeton_photo:photo.jeton,cle_import:photo.key,usage_initial:usage})});imported.current.push(result.id);setPhotos(p=>p.filter(x=>x.key!==photo.key));}onImported(imported.current);}catch(e){setNotice(`${(e as Error).message} Les photos déjà ajoutées restent enregistrées.`);}finally{setBusy(false);}}
 if(!open)return <Button secondary title="Importer depuis une annonce Airbnb ou Booking" onPress={()=>setOpen(true)}/>;
 return <View style={{padding:18,gap:14,borderRadius:20,backgroundColor:'#f0f4e8'}}><Text style={{fontSize:18,color:colors.ink}}>Depuis mon annonce Airbnb ou Booking</Text><TextInput accessibilityLabel="Lien de mon annonce" placeholder="https://www.airbnb.fr/rooms/…" value={url} onChangeText={setUrl} editable={!busy&&!homeCreated} autoCapitalize="none" style={{borderWidth:1,borderColor:'#ccd5bf',padding:13,borderRadius:12}}/><Button secondary title={busy?'Chargement…':'Récupérer les photos'} disabled={busy||homeCreated||!url.trim()} onPress={()=>void find()}/>{!!notice&&<Text accessibilityLiveRegion="polite">{notice}</Text>}<View style={{flexDirection:'row',flexWrap:'wrap',gap:10}}>{photos.map(p=><Pressable key={p.key} accessibilityRole="checkbox" accessibilityState={{checked:p.selected}} accessibilityLabel="Sélectionner cette photo" disabled={busy} onPress={()=>setPhotos(items=>items.map(x=>x.key===p.key?{...x,selected:!x.selected}:x))} style={{width:'46%',padding:5,borderWidth:2,borderColor:p.selected?'#4d683c':'transparent',borderRadius:12}}><Image source={{uri:p.preview}} style={{width:'100%',aspectRatio:1.4,borderRadius:8}}/><Text>{p.selected?'✓ Sélectionnée':'Non sélectionnée'}</Text></Pressable>)}</View>{!!photos.length&&<Button title={`Ajouter ${photos.filter(p=>p.selected).length} photos sélectionnées`} disabled={busy||!photos.some(p=>p.selected)} onPress={()=>void add()}/>}</View>;
}
